// // File generated by FlutterFire CLI.
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//
//       return web;
//   }
//
//   // 🔥 YAHA APNA FIREBASE CONFIG PASTE KARO
//   static const FirebaseOptions web = FirebaseOptions(
//       apiKey: "AIzaSyCE5-cq56m8y6ncDZkM_Y6W0NmSJ-XMTyU",
//       authDomain: "vitty-base.firebaseapp.com",
//       projectId: "vitty-base",
//       storageBucket: "vitty-base.firebasestorage.app",
//       messagingSenderId: "130321581049",
//       appId: "1:130321581049:web:ebfc596182f5ec808bb328",
//       measurementId: "G-DP60DNWF94"
//   );
// }


// lib/firebase_options.dart

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 🔹 Web config (agar use nahi kar rahe, dummy bhi reh sakta hai)
  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCE5-cq56m8y6ncDZkM_Y6W0NmSJ-XMTyU",
      authDomain: "vitty-base.firebaseapp.com",
      projectId: "vitty-base",
      storageBucket: "vitty-base.firebasestorage.app",
      messagingSenderId: "130321581049",
      appId: "1:130321581049:web:ebfc596182f5ec808bb328",
      measurementId: "G-DP60DNWF94"
  );

  // 🔹 Android config
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCE5-cq56m8y6ncDZkM_Y6W0NmSJ-XMTyU",
    appId: "1:130321581049:web:ebfc596182f5ec808bb328",
    messagingSenderId: "130321581049",
    projectId: "vitty-base",
    storageBucket: "vitty-base.firebasestorage.app",
  );

  // 🔹 iOS config
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyAH-GqVx9k-Rn5M9ryn8dYXY4GrzNcMLa4",
    appId: "1:130321581049:ios:9482919b507608768bb328",
    messagingSenderId: "130321581049",
    projectId: "vitty-base",
    storageBucket: "vitty-base.firebasestorage.app",
    iosClientId: '717280964807-tb0as8l7bun9n349gjftd6vdu7341ndi.apps.googleusercontent.com',
    iosBundleId: 'com.ai.vitty', // 🔁 yaha tumhara bundle id
  );

  // 🔹 macOS (agar nahi use kar rahe, iOS jaisa hi ya dummy)
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyCE5-cq56m8y6ncDZkM_Y6W0NmSJ-XMTyU",
    appId: "1:130321581049:web:ebfc596182f5ec808bb328",
    messagingSenderId: "130321581049",
    projectId: "vitty-base",
    storageBucket: "vitty-base.firebasestorage.app",
    iosClientId: '717280964807-tb0as8l7bun9n349gjftd6vdu7341ndi.apps.googleusercontent.com',
    iosBundleId: 'com.vitty.ai', // 🔁 yaha tumhara bundle id
  );
}
